[project]
name = "dspsvdd"
version = "0.1.0"
description = "Deep Structure-Preserving SVDD (encoder-only) for One-Class Anomaly Detection"
requires-python = ">=3.9"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
